# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-24 01:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodtaskerapp', '0006_auto_20171115_0318'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='locations',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
